openai_api_key: "your_openai_api_key"
google_speech_to_text_api_key: "your_google_speech_to_text_api_key"
google_text_to_speech_api_key: "your_google_text_to_speech_api_key"
huggingface_api_key: "your_huggingface_api_key"